### ISSUE TITLE
undefined method `join' Enumerator on push

### ISSUE THREAD

**Issue by LordGaav** [gitlabhq/gitlab-shell#223]
I get the following message on a Git push to a Gitlab 7.8.4 and gitlab-shell 2.5.4.

```
Counting objects: 14, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 1.56 KiB | 0 bytes/s, done.
Total 11 (delta 2), reused 0 (delta 0)
remote: /home/git/gitlab-shell/lib/gitlab_net.rb:16:in `check_access': undefined method `join' for #<Enumerator:0x00000002896078> (NoMethodError)
remote: 	from /home/git/gitlab-shell/lib/gitlab_access.rb:22:in `exec'
remote: 	from hooks/pre-receive:13:in `<main>'
To git@xxxl:Lord_Gaav/arduino-plants.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@xxx:Lord_Gaav/arduino-plants.git'

```

It seems to be caused by this line https://github.com/gitlabhq/gitlab-shell/blob/master/lib/gitlab_access.rb#L17 , which results in an Enumerator that https://github.com/gitlabhq/gitlab-shell/blob/master/lib/gitlab_net.rb#L16 cannot handle.

I fixed it on my installation (for now) by applying this change:

```patch
diff --git a/lib/gitlab_net.rb b/lib/gitlab_net.rb
index d5bda88..39560a4 100644
--- a/lib/gitlab_net.rb
+++ b/lib/gitlab_net.rb
@@ -13,6 +13,11 @@ class GitlabNet
     project_name = repo.gsub("'", "")
     project_name = project_name.gsub(/\.git\Z/, "")
     project_name = project_name.gsub(/\A\//, "")
+    if changes.kind_of?(Enumerator)
+      ch = []
+      changes.each { |change| ch.push(change) }
+      changes = ch
+    end
     changes = changes.join("\n") unless changes.kind_of?(String)
 
     params = {
```

**Comment by maxlazio** [comment]
@LordGaav Which version of ruby are you using? I suspect this is a duplicate issue of #211

**Comment by LordGaav** [comment]
Ruby 2.1.5 via rbenv

**Comment by nikku** [comment]
The callback executes as a shell command and will not use your custom ruby (i.e. 2.1.5 via rbenv). Instead it uses the system ruby which may be < 2.0.0 depending on your operating system.

**Comment by LordGaav** [comment]
Hmm, that might have been it then. I seem to have run into what is described here: http://stackoverflow.com/questions/940533/how-do-i-set-path-such-that-ssh-userhost-command-works .

It might be a good idea to include a small note in the install/upgrade instructions to put any custom PATH declarations before the PS1 line in .bashrc. Seeing that I'm not the first to run into this issue, this may help other people.

**Comment by oneclickdev** [comment]
I have same issue but on latest gitlab version (gitlab-shell 2.6.0; Ruby 2.1.5; GitLab 7.9.0); 
and your fix helped me;

**Comment by LordGaav** [comment]
In hindsight the fix only only hides the problem. The real problem was that rbenv was not exposed to git-shell, and thus the wrong (system) ruby was used.

**Comment by o1y** [comment]
I use rvm to manage my rubies and run into the same error. By adding the following command to .bashrc (before the PS1 line) the correct ruby version is used in the non-login shell:

<code>source /usr/local/rvm/environments/ruby-2.x.x</code>

How to find the ruby environment:
https://rvm.io/deployment/cron#loading-rvm-environment-files-in-shell-scripts

**Comment by zingmars** [comment]
Doesn't seem to work for me. Even after setting source pointing to the latest version of ruby for the git user it will return the same error. :/

**Comment by arthur-c** [comment]
The problem is still here for me too, I have to stay in v2.4.1. No change with ruby 2.2.2. I use rbenv to manage my rubies.

**Comment by maxlazio** [comment]
GitLab supports ruby 2.0.x and 2.1.x, see [requirements doc](https://gitlab.com/gitlab-org/gitlab-ce/blob/7-10-stable/doc/install/requirements.md#ruby-versions).

**Comment by omkelderman** [comment]
I have the same problem, and i did some debugging and have found some interesting things.

First some details about my system:
* `/usr/bin/ruby` points to `/etc/alternatives/ruby` which points to `/usr/bin/ruby1.9.1`, which has version `ruby 1.9.3p194`
* `/usr/local/bin/ruby` is an ruby install from source as described by the installation guide from gitlab, which is version `ruby 2.1.6p336`
* other than that there is no existing ruby-executable on my system

That said, gitlab itself is using version 2.1.6, it syas so in ther web-interface.

I edited the file mentioned at the top of this page (lib/gitlab_net.rb) and added these two lines:
```ruby
puts "PATH: #{ENV['PATH']}"
puts "Ruby version: #{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
```

After that i did an push using http and a push using ssh with the following results:
HTTP:
```
remote: /home/git/gitlab-shell/lib/gitlab_net.rb:18:in `check_access': undefined
 method `join' for #<Enumerator:0x00000001ef2f08> (NoMethodError)
remote:         from /home/git/gitlab-shell/lib/gitlab_access.rb:23:in `exec'
remote:         from hooks/pre-receive:13:in `<main>'
remote: PATH: /usr/lib/git-core:/usr/bin:/usr/lib/git-core:/usr/bin:/home/git/gi
tlab/vendor/bundle/ruby/2.1.0/bin:/usr/local/bin:/usr/local/apache-maven/apache-
maven-3.1.1/bin:/usr/local/android-sdk-linux/tools:/usr/local/android-sdk-linux/
platform-tools:/usr/bin:/bin:/usr/local/games:/usr/games
remote: Ruby version: 1.9.3-p194
```
SSH:
```
remote: PATH: /usr/lib/git-core:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr
/bin/X11:/usr/games
remote: Ruby version: 2.1.6-p336
```

On the http one, the PATH environment variable is pretty long (and yes, i have some android-sdk shit installed on my server :P), but more importantly, /usr/bin is listed first in the path, so it will use ruby 1.9.3, on the ssh-one the PATH is suddenly a lot shorter, even without all the random android-sdk-stuff, but with X11??, whatever, but there /usr/local/bin is listed first (as it should be), hench the correct version of ruby (2.1.6) will be used.

Oh and, yes, with HTTP it fails, and with SSH ot works perfectly

I wonder how that PATH environment variable gets build on the HTTP one.. As far as i know, i dont do any special PATH-modifications on my system other than a global (/etc/bash.bashrc) change to add android-sdk stuff.

I find it kinda strange that the PATH differs so much for both on them..

Anyone any thoughs on this?

**Comment by Danpiel** [comment]
Got same error on Gitlab 7.10.1 and ruby 2.1.6 (installed via rvm), fix in first comment works, thank you.

**Comment by asyd** [comment]
thanks for the patch :+1:

**Comment by bhuisgen** [comment]
Thanks for the patch! I hope that this fix will be in the next release ...

**Comment by endorfin** [comment]
thanks to LordGaav for the fix!

**Comment by LordGaav** [comment]
For those that have not read the entire thread, the fix I posted at the beginning only hides the real problem. The real solution is to use the right version of Ruby, and if using rbenv/rvm to configure it properly and making sure it loads. As soon as another part of gitlab-shell starts to use new Ruby features my patch will break.

**Comment by endorfin** [comment]
you're right ... i remove your hotfix and set the rbenv ruby version for my gitlab user to 2.1.6. The global version points to 1.9.3
```
sudo su -l gitlab
rbenv local 2.1.6
```

**Comment by ReDetection** [comment]
Could it be automated on install?

**Comment by omkelderman** [comment]
that might work for you, but I don't have any rbenv like thing. My situation is like i described in my previous comment, and as of yet, i have not been able to make gitlab use the right ruby version...

**Comment by bhuisgen** [comment]
I add this to forbid any install of ruby through apt :
```
 # cat /etc/apt/preferences.d/ruby 
Package: ruby*
Pin: origin ""
Pin-Priority: -1
```

Hope it helps someone.

**Comment by sebastian-lenz** [comment]
Hey, I'm having the same problem after upgrading gitlab-shell. The system gitlab-shell runs on ships with ruby 2.0.0p35, I've installed ruby 2.1.6 through rbenv but still users get this error:

```
Compressing objects: 100% (17/17), done.
Writing objects: 100% (19/19), 30.70 KiB | 0 bytes/s, done.
Total 19 (delta 9), reused 0 (delta 0)
remote: /home/git/gitlab-shell/lib/gitlab_net.rb:16:in `check_access': undefined method `join' for #<Enumerator:0x000000029504c8> (NoMethodError)
remote:         from /home/git/gitlab-shell/lib/gitlab_access.rb:23:in `exec'
remote:         from hooks/pre-receive:13:in `<main>'
To http://xyz.com/repro.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://xyz.com/repro.git'
```

Switching back to v2.4.1 of gitlab-shell seems to resolve the error.

Somehow only a part of the users receive this error. I can run the command but I am an administrator. Could the problem be related to incomplete/wrong upgraded user rights in Gitlab?

**Comment by omkelderman** [comment]
@sebastian-lenz what happens if you do what i did (https://github.com/gitlabhq/gitlab-shell/issues/223#issuecomment-98528072)? I wonder if you have the same problem as me and a weird PATH-variable causes gitlab to use the wrong ruby

**Comment by sebastian-lenz** [comment]
@omkelderman Just tried it, found a problem. When pushing via ssh I get
```
remote: Ruby version: 2.1.6-p336
```
but when my colleague tries to push via http he gets
```
remote: Ruby version: 1.9.3-p194
```

Currently I'm trying to figure out where this ruby version comes from...

**Comment by omkelderman** [comment]
@sebastian-lenz pretty much the exact same problem i had :D

as for figuring out where that ruby version came from: u suggest looking at the PATH-variable, i included it for a reason ^^ :P

**Comment by omkelderman** [comment]
also, I have been thinking this for a while now, I may be horribly wrong here, but as far as I understand things right now: if you push over ssh git will make a connection to ssh-server (right?), and somehow gitlab-shell catches that connection and will do its thing. But if you push over http(s) a connection will be made to the webserver, and thus to the gitlab-instance (so NOT gitlab-shell), and somehow that connects to gitlab-shell and does its thing... (disclaimer: this is based on assumptions and I have no clue if this is actually the case)
I'm starting to think that somehow in that process, gitlab contacting gitlab-shell is where stuff may get wrong.. Than again I do not understand how, since my gitlab-instance is using the correct ruby-version.

Could someone either conform my assumptions or completely trash it :P? I kinda wanna know

**Comment by sebastian-lenz** [comment]
When I access the repository through ssh the PATH variable is setup as expected through bash configuration of the git user:
```
remote: PATH: /usr/lib/git-core:/home/git/.rbenv/versions/2.1.6/bin:/home/git/.rbenv/libexec:/home/git/.rbenv/plugins/ruby-build/bin:/home/git/.rbenv/plugins/bundler/bin:/home/git/.rbenv/shims:/home/git/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
```
But the set PATH on http pushes is messed up:
```
remote: PATH: /usr/lib/git-core:/usr/bin:/usr/lib/git-core:/usr/bin:/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin:/home/git/.rbenv/versions/2.1.6/bin:/home/git/.rbenv/libexec:/home/git/.rbenv/plugins/ruby-build/bin:/home/git/.rbenv/plugins/bundler/bin:/home/git/.rbenv/shims:/home/git/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
It contains the path to ruby 2.1.6 but somehow /usr/bin is prepended where an old, unused ruby version is located. I cannot figure out how this happens, I've tested some suspicious users (like the user the web server runs with) but they are all configured to use ruby 2.0.0p35 by default and the PATH never looks like above. Ist it possible that Gitlab changes the PATH somewhere?

**Comment by omkelderman** [comment]
> Ist it possible that Gitlab changes the PATH somewhere?

My assumtion yes, still no clue how tho

**Comment by OtaK** [comment]
:+1: on this isssue, had to patch myself too

**Comment by kanabeat** [comment]
Hi @omkelderman

I'm having the exact same problem as you

Did you find out where the PATH is changed ?

Thanks

**Comment by omkelderman** [comment]
@kanabeat Unfortunately I still have no clue... Luckely I dont use git push/pull over http, so for me it is not really that big of a problem

**Comment by marsuboss** [comment]
@kanabeat 
I changed the path in /etc/environment and it works :+1:

**Comment by OeinTwor** [comment]
same issue, gitlab7.14

i fixed this by 
<pre><code="bash">
   sudo apt-get purge ruby1.9.1
</code></pre>

In my ubuntu ,ruby1.9.1 come from redmine . cz it need rmagick, so i installed ruby-rmagick(redmine's issue say need this),now I uninstalled ruby1.9.1 and ruby-rmagick but everythins is ok.

**Comment by jerbob92** [comment]
I have the same issue when using RVM. 
Now used the patch, but it would be better if it would use the Gitlab ruby.

**Comment by grig191** [comment]
Remove /usr/bin/ruby (its syslink), then
ln -s /usr/local/bin/ruby /usr/bin/ruby

**Comment by sphax3d** [comment]
You can also move this lines :

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

before these lines in the `~/.bashrc` of your gitlab user :

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
