### ISSUE TITLE
when i git push over http/https ，some error founded

### ISSUE THREAD

**Issue by chestarss** [gitlabhq/gitlab-shell#232]
(master>)user@debian:/tmp/test$ git push
Counting objects: 5, done.
Writing objects: 100% (3/3), 255 bytes, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: /home/git/gitlab-shell/lib/gitlab_net.rb:16:in `check_access': undefined method `join' for #<Enumerator:0x000000022c2430> (NoMethodError)
remote: 	from /home/git/gitlab-shell/lib/gitlab_access.rb:23:in `exec'
remote: 	from hooks/pre-receive:13:in `<main>'
To http:///myurl/user/test.gi
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://myurl/user/test.git'

---
so i change file gitlab_net.rb like this , it works.
git@hostname:~/gitlab-shell/lib$ diff gitlab_net.rb gitlab_net.rb.bak 
16,17c16
< #    changes = changes.join("\n") unless changes.kind_of?(String)
<     changes = changes.next.split(" ").join("\n") 
\---
\>     changes = changes.join("\n") unless changes.kind_of?(String)

**Comment by chestarss** [comment]
---
git@hostname:~/gitlab-shell/lib$ diff gitlab_net.rb gitlab_net.rb.bak 
16,20c16
<     if changes.respond_to?(:join) 
<     	changes = changes.join("\n") unless changes.kind_of?(String)
<     else
<     	changes = changes.next.split(" ").join("\n")  
<     end
\---
\>     changes = changes.join("\n") unless changes.kind_of?(String)
---
