### ISSUE TITLE
Redis Sentinel  No sentinels available

### ISSUE THREAD

**Issue by mohaijiang** [gitlabhq/gitlab-shell#255]
I tried to configure gitlab-shell with redis sentinel. I tried many times, but all failed. Is there anybody who has encountered a similar problem?

	git@05e501a59f95:~/gitlab-shell/bin$ ./check 
	Check GitLab API access: OK
	Access to /home/git/.ssh/authorized_keys: OK
	Send ping to redis server: /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:567:in 'sentinel_detect': No sentinels available. (Redis::CannotConnectError)
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:571:in 'resolve_master'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:535:in 'resolve'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:331:in 'establish_connection'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:101:in 'block in connect'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:293:in 'with_reconnect'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:100:in 'connect'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:364:in 'ensure_connected'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:221:in 'block in process'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:306:in 'logging'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:220:in 'process'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:120:in 'call'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis.rb:149:in 'block in ping'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis.rb:58:in 'block in synchronize'
		from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in 'mon_synchronize'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis.rb:58:in 'synchronize'
		from /home/git/gitlab-shell/lib/vendor/redis/lib/redis.rb:148:in 'ping'
		from ./check:35:in '<main>'
and my config.yml  is 

	---
	user: git
	gitlab_url: http://localhost/
	http_settings:
	  self_signed_cert: false
	auth_file: "/home/git/.ssh/authorized_keys"
	redis:
	  bin: "/usr/bin/redis-cli"
	  namespace: resque:gitlab
	  #socket: "/var/run/redis/redis.sock"
	  #host: redis1
	  #port: 6379
	  sentinels:
	    -
	      host: redis-sentinel1
	      port: 26379
	    -
	      host: redis-sentinel2
	      port: 26379
	    -
	      host: redis-sentinel3
	      port: 26379

	log_level: INFO
	audit_usernames: false

and my redis-sentinel info is 

	git@05e501a59f95:~/gitlab-shell$ redis-cli -h redis-sentinel1 -p 26379
	redis-sentinel1:26379> info
	# Server
	redis_version:3.2.8
	redis_git_sha1:00000000
	redis_git_dirty:0
	redis_build_id:36c619aa94c6572b
	redis_mode:sentinel
	os:Linux 3.10.0-514.10.2.el7.x86_64 x86_64
	arch_bits:64
	multiplexing_api:epoll
	gcc_version:4.9.2
	process_id:1
	run_id:b887a0ddcdd9dab5606b8e2c880d20056e409b39
	tcp_port:26379
	uptime_in_seconds:7721
	uptime_in_days:0
	hz:12
	lru_clock:14631462
	executable:/data/redis-sentinel
	config_file:/usr/local/etc/redis/sentinel.conf

	# Clients
	connected_clients:3
	client_longest_output_list:0
	client_biggest_input_buf:0
	blocked_clients:0

	# CPU
	used_cpu_sys:6.95
	used_cpu_user:3.95
	used_cpu_sys_children:0.00
	used_cpu_user_children:0.00

	# Stats
	total_connections_received:36
	total_commands_processed:22366
	instantaneous_ops_per_sec:1
	total_net_input_bytes:1234727
	total_net_output_bytes:134892
	instantaneous_input_kbps:0.02
	instantaneous_output_kbps:0.01
	rejected_connections:0
	sync_full:0
	sync_partial_ok:0
	sync_partial_err:0
	expired_keys:0
	evicted_keys:0
	keyspace_hits:0
	keyspace_misses:0
	pubsub_channels:0
	pubsub_patterns:0
	latest_fork_usec:0
	migrate_cached_sockets:0

	# Sentinel
	sentinel_masters:1
	sentinel_tilt:0
	sentinel_running_scripts:0
	sentinel_scripts_queue_length:0
	sentinel_simulate_failure_flags:0
	master0:name=mymaster,status=ok,address=192.168.6.3:6379,slaves=2,sentinels=3

Who can tell me where the problem is？

**Comment by axilleas** [comment]
@mohaijiang can you open this issue in https://gitlab.com/gitlab-org/gitlab-ce/issues instead? It will get more traction there.

**Comment by mohaijiang** [comment]
@axilleas Thanks for guide.
